spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/vocaGenerator
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #테이블 자동 drop 후 create하는 옵션
    properties:
      hibernate:
        format_sql: true
        show_sql: true #sql 쿼리 로그에 띄우기
logging:
  level:
    org.hibernate.sql: debug
  #org.hibernate.type: trace